import { Poppins } from "next/font/google";
import "@/styles/globals.css";
import { ThemeProvider } from "@/context/GlobalComponent";

const font = Poppins({
  subsets: ["latin"],
  weight: ["300", "500", "400", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
